### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by hugofqueiros** [cedx/david.gulp#4]
.../node_modules/gulp-david/index.js:8
const Checker=require('./lib/checker');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../gulpfile.js:8:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

nodejs: v0.12.8
npm: 2.14.9

**Comment by hugofqueiros** [comment]
I see now that as from version 0.3.0 the required node version was raised.
Version 2.3.0 works correctly for node v0.12.8.
Can you lower your requirements for node?

**Comment by cedx** [comment]
Unfortunately, the new code uses many features from ECMAScript 2015 (ES6). In fact, the version 0.3.x is a port of version 0.2.x to ES6, with very few additions (just the `errorDepCount` and `ignore` options).

So Node.js 0.12.x and lower can't use this new release. You must upgrade your Node.js runtime to version 4.x, or stick with version 0.2.3 of the package.
