### ISSUE TITLE
Removing david.reporter causes issues with previously-working code

### ISSUE THREAD

**Issue by sheeley** [cedx/david.gulp#7]
FYI - this change to the API is breaking, so it might be worth considering a major version bump. I'm strongly suggesting this because this causes currently working builds to die.

The error looks like this, in case anyone else is searching:
```js
TypeError: Cannot read property 'on' of undefined
    at Checker.Readable.pipe (_stream_readable.js:481:7)
    at Gulp.<anonymous> (gulpfile.babel.js:45:6)
    at module.exports (/Users/jsheeley/git/lumen/api/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jsheeley/git/lumen/api/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jsheeley/git/lumen/api/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/jsheeley/git/lumen/api/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3
```
The fix is removing `.pipe(david.reporter)` from your gulpfile.

**Comment by cedx** [comment]
I'm following the [Semantic Versioning](http://semver.org). As my project is still in major version zero (0.y.z), I only have to increment the Y version component when I introduce some breaking changes.

This is what I've done in the last release : the version number raised from 0.3.x to 0.4.x.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

If no new issue come in the next month, maybe I'll release the first 1.x version :sweat_smile:
