### ISSUE TITLE
Travis CI Issue @ 0.4.1

### ISSUE THREAD

**Issue by shellscape** [cedx/david.gulp#8]
Running into a very strange problem with Travis CI and gulp-david. Please see the log for this build: https://travis-ci.org/shellscape/clearcut/builds/107140438

The specific error being thrown by gulp-david is:

```
[01:46:38] TypeError: Cannot read property 'on' of undefined
    at Checker.Readable.pipe (_stream_readable.js:481:7)
    at Gulp.<anonymous> (/home/travis/build/shellscape/clearcut/gulpfile.js:13:6)
    at module.exports (/home/travis/build/shellscape/clearcut/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/travis/build/shellscape/clearcut/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/shellscape/clearcut/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/travis/build/shellscape/clearcut/node_modules/orchestrator/index.js:134:8)
    at /home/travis/.nvm/versions/node/v5.5.0/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

I reverted back to `^0.3.0` and all was well. (https://travis-ci.org/shellscape/clearcut/builds/107142228) Seems that `0.4.1` has issues with travis once again.

**Comment by cedx** [comment]
See the [changelog](https://github.com/cedx/david.gulp/blob/master/CHANGELOG.md): version 0.4.x has introduced some breaking changes. You must update your code by removing the reporter as it is now merged into the plugin.

See issue #5 on why this decision was taken.

**Comment by shellscape** [comment]
@cedx thanks for pointing that out. That's README-worthy information.
